// <auto-generated />
using System;
using BeautyBooking.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeautyBooking.EF.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260328073701_update-staff_day_off-DateTimeConvertDateOnly-Date")]
    partial class updatestaff_day_offDateTimeConvertDateOnlyDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BeautyBooking.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("appointment_date");

                    b.Property<int>("AppointmentStatus")
                        .HasColumnType("int")
                        .HasColumnName("appointment_status");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<int>("EndTime")
                        .HasColumnType("int")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsActived")
                        .HasColumnType("bit")
                        .HasColumnName("is_actived");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<int>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("staff_id");

                    b.Property<int>("StartTime")
                        .HasColumnType("int")
                        .HasColumnName("start_time");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_price");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_appointments");

                    b.HasIndex("StaffId")
                        .HasDatabaseName("ix_appointments_staff_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_appointments_user_id");

                    b.ToTable("appointments", (string)null);
                });

            modelBuilder.Entity("BeautyBooking.Entities.AppointmentService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("appointment_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<int>("DurationAtBooking")
                        .HasColumnType("int")
                        .HasColumnName("duration_at_booking");

                    b.Property<bool>("IsActived")
                        .HasColumnType("bit")
                        .HasColumnName("is_actived");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<decimal>("PriceAtBooking")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price_at_booking");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("service_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_appointment_services");

                    b.HasIndex("AppointmentId")
                        .HasDatabaseName("ix_appointment_services_appointment_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_appointment_services_service_id");

                    b.ToTable("appointment_services", (string)null);
                });

            modelBuilder.Entity("BeautyBooking.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActived")
                        .HasColumnType("bit")
                        .HasColumnName("is_actived");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("BeautyBooking.Entities.HelpdeskCatalog", b =>
                {
                    b.Property<int>("CatalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("catalog_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CatalogId"));

                    b.Property<bool>("IsActived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_actived");

                    b.Property<string>("KeyCatalog")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("key_catalog");

                    b.Property<string>("NameVn")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("name_vn");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("url");

                    b.HasKey("CatalogId")
                        .HasName("pk_helpdesk_catalogs");

                    b.ToTable("helpdesk_catalogs", (string)null);
                });

            modelBuilder.Entity("BeautyBooking.Entities.HelpdeskContent", b =>
                {
                    b.Property<int>("ContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("content_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContentId"));

                    b.Property<int>("CatalogId")
                        .HasColumnType("int")
                        .HasColumnName("catalog_id");

                    b.Property<string>("ContentDetail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content_detail");

                    b.HasKey("ContentId")
                        .HasName("pk_helpdesk_contents");

                    b.HasIndex("CatalogId")
                        .HasDatabaseName("ix_helpdesk_contents_catalog_id");

                    b.ToTable("helpdesk_contents", (string)null);
                });

            modelBuilder.Entity("BeautyBooking.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActived")
                        .HasColumnType("bit")
                        .HasColumnName("is_actived");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_services");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_services_category_id");

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("BeautyBooking.Entities.StaffDayOff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<bool>("IsActived")
                        .HasColumnType("bit")
                        .HasColumnName("is_actived");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("reason");

                    b.Property<int>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("staff_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_staff_day_offs");

                    b.HasIndex("StaffId")
                        .HasDatabaseName("ix_staff_day_offs_staff_id");

                    b.ToTable("staff_day_offs", (string)null);
                });

            modelBuilder.Entity("BeautyBooking.Entities.StaffProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActived")
                        .HasColumnType("bit")
                        .HasColumnName("is_actived");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_staff_profiles");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_staff_profiles_user_id");

                    b.ToTable("staff_profiles", (string)null);
                });

            modelBuilder.Entity("BeautyBooking.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActived")
                        .HasColumnType("bit")
                        .HasColumnName("is_actived");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.Property<int?>("WardId")
                        .HasColumnType("int")
                        .HasColumnName("ward_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("WardId")
                        .HasDatabaseName("ix_users_ward_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BeautyBooking.Entities.WebsiteLocalization", b =>
                {
                    b.Property<string>("KeyLocalization")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("key_localization");

                    b.Property<bool>("IsActived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_actived");

                    b.Property<string>("Localization")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("localization");

                    b.HasKey("KeyLocalization")
                        .HasName("pk_website_localizations");

                    b.ToTable("website_localizations", (string)null);
                });

            modelBuilder.Entity("BeautyBooking.Entities.WebsiteLocalizationWard", b =>
                {
                    b.Property<int>("WardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ward_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WardId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)")
                        .HasColumnName("full_name");

                    b.Property<string>("FullNameEn")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)")
                        .HasColumnName("full_name_en");

                    b.Property<bool>("IsActived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_actived");

                    b.Property<string>("KeyLocalization")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("key_localization");

                    b.Property<double>("Latitude")
                        .HasColumnType("float")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("name");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("name_en");

                    b.Property<int?>("WardPid")
                        .HasColumnType("int")
                        .HasColumnName("ward_pid");

                    b.HasKey("WardId")
                        .HasName("pk_website_localization_wards");

                    b.HasIndex("KeyLocalization")
                        .HasDatabaseName("ix_website_localization_wards_key_localization");

                    b.ToTable("website_localization_wards", (string)null);
                });

            modelBuilder.Entity("BeautyBooking.Entities.WorkSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int")
                        .HasColumnName("day_of_week");

                    b.Property<int>("EndTime")
                        .HasColumnType("int")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsActived")
                        .HasColumnType("bit")
                        .HasColumnName("is_actived");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<int>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("staff_id");

                    b.Property<int>("StartTime")
                        .HasColumnType("int")
                        .HasColumnName("start_time");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_work_schedules");

                    b.HasIndex("StaffId")
                        .HasDatabaseName("ix_work_schedules_staff_id");

                    b.ToTable("work_schedules", (string)null);
                });

            modelBuilder.Entity("ServiceStaffProfile", b =>
                {
                    b.Property<int>("ServicesId")
                        .HasColumnType("int")
                        .HasColumnName("services_id");

                    b.Property<int>("StaffProfilesId")
                        .HasColumnType("int")
                        .HasColumnName("staff_profiles_id");

                    b.HasKey("ServicesId", "StaffProfilesId")
                        .HasName("pk_service_staff_profile");

                    b.HasIndex("StaffProfilesId")
                        .HasDatabaseName("ix_service_staff_profile_staff_profiles_id");

                    b.ToTable("service_staff_profile", (string)null);
                });

            modelBuilder.Entity("BeautyBooking.Entities.Appointment", b =>
                {
                    b.HasOne("BeautyBooking.Entities.StaffProfile", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_appointments_staff_profiles_staff_id");

                    b.HasOne("BeautyBooking.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_appointments_users_user_id");

                    b.Navigation("Staff");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeautyBooking.Entities.AppointmentService", b =>
                {
                    b.HasOne("BeautyBooking.Entities.Appointment", "Appointment")
                        .WithMany("AppointmentServices")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_appointment_services_appointments_appointment_id");

                    b.HasOne("BeautyBooking.Entities.Service", "Service")
                        .WithMany("AppointmentServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_appointment_services_services_service_id");

                    b.Navigation("Appointment");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("BeautyBooking.Entities.HelpdeskContent", b =>
                {
                    b.HasOne("BeautyBooking.Entities.HelpdeskCatalog", "HelpdeskCatalog")
                        .WithMany("HelpdeskContents")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_helpdesk_contents_helpdesk_catalogs_catalog_id");

                    b.Navigation("HelpdeskCatalog");
                });

            modelBuilder.Entity("BeautyBooking.Entities.Service", b =>
                {
                    b.HasOne("BeautyBooking.Entities.Category", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_services_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BeautyBooking.Entities.StaffDayOff", b =>
                {
                    b.HasOne("BeautyBooking.Entities.StaffProfile", "Staff")
                        .WithMany("StaffDayOffs")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_staff_day_offs_staff_profiles_staff_id");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("BeautyBooking.Entities.StaffProfile", b =>
                {
                    b.HasOne("BeautyBooking.Entities.User", "User")
                        .WithOne("StaffProfile")
                        .HasForeignKey("BeautyBooking.Entities.StaffProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_staff_profiles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeautyBooking.Entities.User", b =>
                {
                    b.HasOne("BeautyBooking.Entities.WebsiteLocalizationWard", "Ward")
                        .WithMany()
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_website_localization_wards_ward_id");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("BeautyBooking.Entities.WebsiteLocalizationWard", b =>
                {
                    b.HasOne("BeautyBooking.Entities.WebsiteLocalization", "WebsiteLocalization")
                        .WithMany("WebsiteLocalizationWards")
                        .HasForeignKey("KeyLocalization")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_website_localization_wards_website_localizations_key_localization");

                    b.Navigation("WebsiteLocalization");
                });

            modelBuilder.Entity("BeautyBooking.Entities.WorkSchedule", b =>
                {
                    b.HasOne("BeautyBooking.Entities.StaffProfile", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_work_schedules_staff_profiles_staff_id");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("ServiceStaffProfile", b =>
                {
                    b.HasOne("BeautyBooking.Entities.Service", null)
                        .WithMany()
                        .HasForeignKey("ServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_staff_profile_services_services_id");

                    b.HasOne("BeautyBooking.Entities.StaffProfile", null)
                        .WithMany()
                        .HasForeignKey("StaffProfilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_staff_profile_staff_profiles_staff_profiles_id");
                });

            modelBuilder.Entity("BeautyBooking.Entities.Appointment", b =>
                {
                    b.Navigation("AppointmentServices");
                });

            modelBuilder.Entity("BeautyBooking.Entities.Category", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("BeautyBooking.Entities.HelpdeskCatalog", b =>
                {
                    b.Navigation("HelpdeskContents");
                });

            modelBuilder.Entity("BeautyBooking.Entities.Service", b =>
                {
                    b.Navigation("AppointmentServices");
                });

            modelBuilder.Entity("BeautyBooking.Entities.StaffProfile", b =>
                {
                    b.Navigation("StaffDayOffs");
                });

            modelBuilder.Entity("BeautyBooking.Entities.User", b =>
                {
                    b.Navigation("StaffProfile");
                });

            modelBuilder.Entity("BeautyBooking.Entities.WebsiteLocalization", b =>
                {
                    b.Navigation("WebsiteLocalizationWards");
                });
#pragma warning restore 612, 618
        }
    }
}
