// <auto-generated />
using System;
using BeautyBooking.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeautyBooking.EF.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260319093031_Update_CSDL_L2")]
    partial class Update_CSDL_L2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BeautyBooking.Entities.HelpdeskCatalog", b =>
                {
                    b.Property<int>("CatalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("catalog_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CatalogId"));

                    b.Property<bool>("IsActived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_actived");

                    b.Property<string>("KeyCatalog")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("key_catalog");

                    b.Property<string>("NameVn")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("name_vn");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("url");

                    b.HasKey("CatalogId")
                        .HasName("pk_helpdesk_catalogs");

                    b.ToTable("helpdesk_catalogs", (string)null);
                });

            modelBuilder.Entity("BeautyBooking.Entities.HelpdeskContent", b =>
                {
                    b.Property<int>("ContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("content_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContentId"));

                    b.Property<int>("CatalogId")
                        .HasColumnType("int")
                        .HasColumnName("catalog_id");

                    b.Property<string>("ContentDetail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content_detail");

                    b.HasKey("ContentId")
                        .HasName("pk_helpdesk_contents");

                    b.HasIndex("CatalogId")
                        .HasDatabaseName("ix_helpdesk_contents_catalog_id");

                    b.ToTable("helpdesk_contents", (string)null);
                });

            modelBuilder.Entity("BeautyBooking.Entities.WebsiteLocalization", b =>
                {
                    b.Property<string>("KeyLocalization")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("key_localization");

                    b.Property<bool>("IsActived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_actived");

                    b.Property<string>("Localization")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("localization");

                    b.HasKey("KeyLocalization")
                        .HasName("pk_website_localizations");

                    b.ToTable("website_localizations", (string)null);
                });

            modelBuilder.Entity("BeautyBooking.Entities.WebsiteLocalizationWard", b =>
                {
                    b.Property<int>("WardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ward_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WardId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)")
                        .HasColumnName("full_name");

                    b.Property<string>("FullNameEn")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)")
                        .HasColumnName("full_name_en");

                    b.Property<bool>("IsActived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_actived");

                    b.Property<string>("KeyLocalization")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("key_localization");

                    b.Property<double>("Latitude")
                        .HasColumnType("float")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("name");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("name_en");

                    b.Property<int?>("WardPid")
                        .HasColumnType("int")
                        .HasColumnName("ward_pid");

                    b.HasKey("WardId")
                        .HasName("pk_website_localization_wards");

                    b.HasIndex("KeyLocalization")
                        .HasDatabaseName("ix_website_localization_wards_key_localization");

                    b.ToTable("website_localization_wards", (string)null);
                });

            modelBuilder.Entity("BeautyBooking.Entities.HelpdeskContent", b =>
                {
                    b.HasOne("BeautyBooking.Entities.HelpdeskCatalog", "HelpdeskCatalog")
                        .WithMany("HelpdeskContents")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_helpdesk_contents_helpdesk_catalogs_catalog_id");

                    b.Navigation("HelpdeskCatalog");
                });

            modelBuilder.Entity("BeautyBooking.Entities.WebsiteLocalizationWard", b =>
                {
                    b.HasOne("BeautyBooking.Entities.WebsiteLocalization", "WebsiteLocalization")
                        .WithMany("WebsiteLocalizationWards")
                        .HasForeignKey("KeyLocalization")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_website_localization_wards_website_localizations_key_localization");

                    b.Navigation("WebsiteLocalization");
                });

            modelBuilder.Entity("BeautyBooking.Entities.HelpdeskCatalog", b =>
                {
                    b.Navigation("HelpdeskContents");
                });

            modelBuilder.Entity("BeautyBooking.Entities.WebsiteLocalization", b =>
                {
                    b.Navigation("WebsiteLocalizationWards");
                });
#pragma warning restore 612, 618
        }
    }
}
